<aside class="logo">
	<a class="social" id="twitter" href="https://twitter.com/tehsuck"><img src="/assets/img/twitter-square-black.png"></a>
	<a class="social" id="instagram" href="https://instagram.com/tehsuck"><img src="/assets/img/instagram-square-black.png"></a>
	<a href="{{ baseurl }}">
		<img src="http://www.gravatar.com/avatar/{{ pkg.gravatar }}.png?s=80" class="gravatar">
	</a>
	<span class="logo-prompt">{{ pkg.prompt }}</span>
	<a class="social" id="github" href="https://github.com/chiefy"><img src="/assets/img/github-square-black.png"></a>
	<a class="social" id="linkedin" href="https://www.linkedin.com/in/chief"><img src="/assets/img/linkedin-square-black.png"	></a>
</aside>
